
export const pageCategories = [
  "Abortion Service",
  "Abruzzo Restaurant",
  "Academic Camp",
  "Accessories",
  "Accountant",
  "Acehnese Restaurant",
  "Actor",
  "Acupuncturist",
  "Addiction Resources Center",
  "Addiction Service",
  "Addiction Treatment Center",
  "Adoption Service",
  "Adult Entertainment Service",
  "Aerospace Company",
  "Afghan Restaurant",
  "African Methodist Episcopal Church",
  "African Restaurant",
  "AIDS Resource Center",
  "Aircraft Manufacturer",
  "Airline Company",
  "Airline Industry Service",
  "Airport",
  "Airport Gate",
  "Airport Lounge",
  "Airport Shuttle Service",
  "Airport Terminal",
  "Album",
  "Alcohol Addiction Treatment Center",
  "Allergist",
  "Alternative & Holistic Health Service",
  "Amateur Photographer",
  "Amateur Sports League",
  "Amateur Sports Team",
  "American Restaurant",
  "Andhra Restaurant",
  "Anesthesiologist",
  "Anglican Church",
  "Anhui Restaurant",
  "Animal Rescue Service",
  "Animal Shelter",
  "Animation Studio",
  "Antique Store",
  "Aosta Restaurant",
  "Apartment & Condo Building",
  "Apostolic Church",
  "App Page",
  "Apparel & Clothing",
  "Apparel Distributor",
  "Appliance Manufacturer",
  "Appliance Repair Service",
  "Appliance Store",
  "Appliances",
  "Aquatic Pet Store",
  "Arabian Restaurant",
  "Arboretum",
  "Archaeological Service",
  "Archery Range",
  "Archery Shop",
  "Architectural Designer",
  "Architectural Tour Agency",
  "Argentinian Restaurant",
  "Armed Forces",
  "Armenian Restaurant",
  "Aromatherapy Service",
  "Art",
  "Art Restoration Service",
  "Art School",
  "Art Tour Agency",
  "Article",
  "Artist",
  "Arts & Crafts Store",
  "Arts & Humanities Website",
  "Asian Fusion Restaurant",
  "Asian Restaurant",
  "Assemblies of God",
  "Astrologist",
  "Astrologist & Psychic",
  "Athlete",
  "ATV Recreation Park",
  "ATV Rental",
  "Auction House",
  "Audio Visual Equipment Store",
  "Audiologist",
  "Australian Restaurant",
  "Austrian Restaurant",
  "Author",
  "Auto Detailing Service",
  "Automated Teller Machine (ATM)",
  "Automation Service",
  "Automotive Body Shop",
  "Automotive Consultant",
  "Automotive Customization Shop",
  "Automotive Glass Service",
  "Automotive Leasing Service",
  "Automotive Manufacturer",
  "Automotive Parts Store",
  "Automotive Registration Center",
  "Automotive Repair Shop",
  "Automotive Restoration Service",
  "Automotive Service",
  "Automotive Shipping Service",
  "Automotive Storage Facility",
  "Automotive Store",
  "Automotive Wheel Polishing Service",
  "Automotive Window Tinting Service",
  "Aviation Repair Station",
  "Aviation School",
  "Avionics Shop",
  "Awadhi Restaurant",
  "Awning Supplier",
  "Azerbaijani Restaurant",
  "Baby & Children’s Clothing Store",
  "Baby Goods/Kids Goods",
  "Babysitter",
  "Baden Restaurant",
  "Badminton Court",
  "Bagel Shop",
  "Bags & Luggage Company",
  "Bags & Luggage Store",
  "Bags/Luggage",
  "Bail Bondsmen",
  "Bakery",
  "Balinese Restaurant",
  "Balloonport",
  "Ballroom",
  "Band",
  "Bank",
  "Bank Equipment & Service",
  "Bankruptcy Lawyer",
  "Baptist Church",
  "Bar",
  "Bar & Grill",
  "Barbecue Restaurant",
  "Barber Shop",
  "Bartending School",
  "Bartending Service",
  "Baseball Field",
  "Baseball Stadium",
  "Basilicata Restaurant",
  "Basketball Court",
  "Basketball Stadium",
  "Basque Restaurant",
  "Batting Cage",
  "Bavarian Restaurant",
  "Bay",
  "Beach",
  "Beach Resort",
  "Beauty Salon",
  "Beauty Store",
  "Beauty Supplier",
  "Beauty Supply Store",
  "Beauty, Cosmetic & Personal Care",
  "Bed and Breakfast",
  "Beer Bar",
  "Beer Garden",
  "Beijing Restaurant",
  "Belarusian Restaurant",
  "Belgian Restaurant",
  "Belizean Restaurant",
  "Bengali/Bangladeshi Restaurant",
  "Betawinese Restaurant",
  "Bicycle Repair Service",
  "Bicycle Shop",
  "Big Box Retailer",
  "Bike Rental",
  "Bike Trail",
  "Biotechnology Company",
  "Blinds & Curtains Store",
  "Blogger",
  "Blood Bank",
  "Board Game",
  "Boat / Sailing Instructor",
  "Boat Rental",
  "Boat Service",
  "Boat Tour Agency",
  "Boat/Ferry Company",
  "Bolivian Restaurant",
  "Book",
  "Book & Magazine Distributor",
  "Book Genre",
  "Book Series",
  "Books & Magazines",
  "Bookstore",
  "Borough",
  "Bossam/Jokbal Restaurant",
  "Botanical Garden",
  "Bottled Water Company",
  "Bottled Water Supplier",
  "Boutique Store",
  "Bowling Alley",
  "Boxing Studio",
  "Brand",
  "Brand/Company Type",
  "Brazilian Restaurant",
  "Breakfast & Brunch Restaurant",
  "Brewery",
  "Bridal Shop",
  "Bridge",
  "British Restaurant",
  "Broadcasting & Media Production Company",
  "Brokerage Firm",
  "Bubble Tea Shop",
  "Buddhist Temple",
  "Buffet Restaurant",
  "Building Material Store",
  "Building Materials",
  "Bulgarian Restaurant",
  "Bunsik Restaurant",
  "Burger Restaurant",
  "Burmese Restaurant",
  "Bus Line",
  "Bus Station",
  "Bus Tour Agency",
  "Business & Economy Website",
  "Business Center",
  "Business Consultant",
  "Business Service",
  "Business Supply Service",
  "Butcher Shop",
  "Cabin",
  "Cabinet & Countertop Store",
  "Cable & Satellite Company",
  "Cafe",
  "Cafeteria",
  "Cajun & Creole Restaurant",
  "Calabrian Restaurant",
  "Cambodian Restaurant",
  "Camera Store",
  "Camera/Photo",
  "Campground",
  "Campus Building",
  "Canadian Restaurant",
  "Canal",
  "Candy Store",
  "Canoe & Kayak Rental",
  "Cantonese Restaurant",
  "Cape Verdean Restaurant",
  "Capital",
  "Capitol Building",
  "Car Dealership",
  "Car Rental",
  "Car Wash",
  "Cargo & Freight Company",
  "Caribbean Restaurant",
  "Carnival Supply Store",
  "Carpenter",
  "Carpet & Flooring Store",
  "Carpet Cleaner",
  "Cash Advance Service",
  "Cash Register Services",
  "Casino",
  "Castilian Restaurant",
  "Caterer",
  "Catholic Church",
  "Cattle Ranch",
  "Caucasian Restaurant",
  "Cave",
  "Cemetery",
  "Champagne Bar",
  "Changhua Restaurant",
  "Charity Organization",
  "Charter Bus Service",
  "Cheese Shop",
  "Chemical Company",
  "Chemical Company Service",
  "Chicken Joint",
  "Chicken Wings Restaurant",
  "Chimney Sweeper",
  "Chinese Restaurant",
  "Chiropractor",
  "Chocolate Shop",
  "Choir",
  "Christian Church",
  "Church",
  "Church of Christ",
  "Church of God",
  "Church of Jesus Christ of Latter-day Saints",
  "Church of the Nazarene",
  "Cigar Lounge",
  "Cinema",
  "Circus",
  "City",
  "City Infrastructure",
  "City Tour Agency",
  "Civic",
  "Climbing Gym",
  "Clinic",
  "Clothing (Brand)",
  "Clothing Store",
  "Club",
  "Clubhouse",
  "Cluster of Excellence",
  "Coach",
  "Cocktail Bar",
  "Coffee Roasters",
  "Coffee Shop",
  "Collectibles Store",
  "College & University",
  "Colombian Restaurant",
  "Colorado Restaurant",
  "Comedy Club",
  "Comic Bookstore",
  "Commercial & Industrial",
  "Commercial & Industrial Equipment Supplier",
  "Commercial & Industrial Equipment Supplier",
  "Commercial Bank",
  "Commercial Equipment",
  "Commercial Real Estate Agency",
  "Community",
  "Community Center",
  "Community College",
  "Community Museum",
  "Community Organization",
  "Community Service",
  "Company",
  "Competition",
  "Comprehensive & Industrial",
  "Computer Company",
  "Computer Repair Service",
  "Computer Store",
  "Computer Training School",
  "Computers & Internet Website",
  "Concert Tour",
  "Concrete Contractor",
  "Congregational Church",
  "Construction Company",
  "Construction Service & Supply",
  "Consulate & Embassy",
  "Consulting Agency",
  "Contemporary Art Museum",
  "Continental Restaurant",
  "Contractor",
  "Convention Center",
  "Cooking School",
  "Copywriting Service",
  "Corporate Lawyer",
  "Corporate Office",
  "Cottage",
  "County",
  "Court",
  "Crane Service",
  "Cricket Ground",
  "Cricket Pitch",
  "Criminal Lawyer",
  "Crisis Intervention Service",
  "Cruise Agency",
  "Cruise Line",
  "Cuban Restaurant",
  "Culinary School",
  "Cultural Center",
  "Cupcake Shop",
  "Currency Exchange",
  "Curtain & Blinds Store",
  "Czech Restaurant",
  "Dairy Farm",
  "Damage Restoration Service",
  "Dance & Night Club",
  "Dance School",
  "Dance Studio",
  "Dancer",
  "Danish Restaurant",
  "Dating Service",
  "Day Care",
  "Debt Collector",
  "Defense Company",
  "Delicatessen",
  "Dentist & Dental Office",
  "Department Store",
  "Dermatologist",
  "Desert",
  "Design & Fashion",
  "Designer",
  "Dessert Shop",
  "Dim Sum Restaurant",
  "Diner",
  "Disc Golf Course",
  "Discount Store",
  "Dive Bar",
  "Dive Instructor",
  "Dive Spot",
  "Divorce & Family Lawyer",
  "DJ",
  "Doctor",
  "Documentary",
  "Dog Day Care Center",
  "Dog Park",
  "Dog Trainer",
  "Dog Walker",
  "Dogsled Tour Agency",
  "Donut Shop",
  "Drafting Service",
  "Drama School",
  "Dress Shop",
  "Driving School",
  "DUI Lawyer",
  "E-cigarette Store",
  "Eastern European Restaurant",
  "Eco Tour Agency",
  "E-commerce Website",
  "Editor",
  "Education",
  "Education Company",
  "Education Website",
  "Educational Consultant",
  "Educational Research Center",
  "Educational Supply Store",
  "Elevator Service",
  "Emergency Rescue Service",
  "Emergency Roadside Service",
  "Emergency Veterinarian",
  "Employment Agency",
  "Endocrinologist",
  "Endodontist",
  "Engineering Service",
  "Entertainer",
  "Entertainment",
  "Entertainment Website",
  "Entrepreneur",
  "Environmental Conservation Organization",
  "Environmental Engineer",
  "Environmental Service",
  "Episode",
  "Equestrian Center",
  "Escape Game Room",
  "Espresso Bar",
  "Estate Planning Lawyer",
  "Ethiopian Restaurant",
  "Ethnic Grocery Store",
  "European Restaurant",
  "Evangelical Church",
  "Event",
  "Event Videographer",
  "Exotic Car Rental",
  "Expat",
  "Eye Doctor",
  "Eyewear",
  "Fabric Store",
  "Face Painting",
  "Factory",
  "Family Doctor",
  "Family Medicine Practice",
  "Family Style Restaurant",
  "Farm",
  "Farmers Market",
  "Farmers' Market",
  "Fashion",
  "Fashion Company",
  "Fashion Designer",
  "Fashion Model",
  "Fast Food Restaurant",
  "Ferry & Boat",
  "Festival",
  "Field of Study",
  "Filipino Restaurant",
  "Film",
  "Film Director",
  "Film/Television studio",
  "Finance",
  "Finance Company",
  "Finance Website",
  "Financial Aid Service",
  "Financial Consultant",
  "Financial Planner",
  "Financial Service",
  "Fire Protection Service",
  "Fireplace Store",
  "Fish & Chips Restaurant",
  "Fish Market",
  "Fishing Spot",
  "Fishing Store",
  "Fitness Boot Camp",
  "Fitness Model",
  "Fitness Trainer",
  "Fjord/Loch",
  "Flea Market",
  "Flight School",
  "Float Spa",
  "Floodplain",
  "Flooring Store",
  "Florist",
  "Food & Beverage",
  "Food & Beverage Company",
  "Food Consultant",
  "Food Delivery Service",
  "Food Stand",
  "Food Tour Agency",
  "Food Truck",
  "Footwear Store",
  "Forestry & Logging",
  "Forestry Service",
  "Forklifts & Excavators",
  "Formal Wear Store",
  "Franchising Service",
  "French Restaurant",
  "Freestyle Rap",
  "Freight Forwarding Service",
  "French Restaurant",
  "Friuli Venezia Giulia Restaurant",
  "Frozen Yogurt Shop",
  "Fruit & Vegetable Store",
  "Fujian Restaurant",
  "Full Gospel Church",
  "Funeral Service & Cemetery",
  "Furniture",
  "Furniture Repair & Upholstery Service",
  "Furniture Store",
  "Game Publisher",
  "Gamer",
  "Games/Toys",
  "Gaming Video Creator",
  "Garage Door Service",
  "Garden Center",
  "Gardener",
  "Gas & Chemical Service",
  "Gas Station",
  "Gastroenterologist",
  "Gastropub",
  "Gay Bar",
  "Gelato Shop",
  "Genealogist",
  "General Dentist",
  "General Litigation",
  "Geo Entity",
  "Geographical Place",
  "Geologic Service",
  "Georgian Restaurant",
  "German Restaurant",
  "Gerontologist",
  "Gift Shop",
  "Glacier",
  "Glass & Mirror Shop",
  "Glass Blower",
  "Glass Manufacturer",
  "Glass Service",
  "Gluten-Free Restaurant",
  "Goan Restaurant",
  "Go-Kart Track",
  "Golf Course & Country Club",
  "Golf Instructor",
  "Granite & Marble Supplier",
  "Graphic Designer",
  "Greek Restaurant",
  "Grocery Store",
  "Guatemalan Restaurant",
  "Guizhou Restaurant",
  "Gujarati Restaurant",
  "Gukbap Restaurant",
  "Gun Range",
  "Gun Store",
  "Gutter Cleaning Service",
  "Gym/Physical Fitness Center",
  "Gymnastics Center",
  "Hainan Restaurant",
  "Hair Extensions Service",
  "Hair Removal Service",
  "Hair Replacement Service",
  "Hair Salon",
  "Haitian Restaurant",
  "Halal Restaurant",
  "Halfway House",
  "Handyman",
  "Hang Gliding Center",
  "Harbor",
  "Hardware Store",
  "Harmonized Page",
  "Hat Store",
  "Hawaiian Restaurant",
  "Health & Wellness Website",
  "Health Food Restaurant",
  "Health Food Store",
  "Health Spa",
  "Health/Beauty",
  "Healthcare Administrator",
  "Heating, Ventilating & Air Conditioning Service",
  "Hedge Fund",
  "Heliport",
  "Henan Restaurant",
  "Hessian Restaurant",
  "High School",
  "Highway",
  "Hiking Trail",
  "Himalayan Restaurant",
  "Hindu Temple",
  "Historical Tour Agency",
  "Hobby Store",
  "Hockey Arena",
  "Hockey Field / Rink",
  "Holiness Church",
  "Home",
  "Home & Garden Store",
  "Home & Garden Website",
  "Home Decor",
  "Home Goods Store",
  "Home Health Care Service",
  "Home Improvement",
  "Home Inspector",
  "Home Mover",
  "Home Security Company",
  "Home Staging Service",
  "Home Theater Store",
  "Home Window Service",
  "Homebrew Supply Store",
  "Honduran Restaurant",
  "Hong Kong Restaurant",
  "Hookah Lounge",
  "Horse Riding School",
  "Horse Trainer",
  "Horseback Riding Center",
  "Horse-Drawn Carriage Service",
  "Hospice",
  "Hospital",
  "Hospitality Service",
  "Hostel",
  "Hot Air Balloon Tour Agency",
  "Hot Dog Joint",
  "Hot Pot Restaurant",
  "Hot Spring",
  "Hotel",
  "Hotel & Lodging",
  "Hotel Bar",
  "Hotel Resort",
  "Hotel Services Company",
  "House Painting",
  "House Sitter",
  "Household Supplies",
  "Housing & Homeless Shelter",
  "Housing Assistance Service",
  "Huaiyang Restaurant",
  "Hubei Restaurant",
  "Hunan Restaurant",
  "Hungarian Restaurant",
  "Hyderabadi Restaurant",
  "Iberian Restaurant",
  "Ice Cream Shop",
  "Ice Skating Rink",
  "Image Consultant",
  "Immigration Lawyer",
  "Imperial Restaurant",
  "Independent Bookstore",
  "Independent Church",
  "Indian Chinese Restaurant",
  "Indian Restaurant",
  "Indo Chinese Restaurant",
  "Indonesian Restaurant",
  "Industrial Company",
  "Information Technology Company",
  "In-Home Service",
  "Inn",
  "Insurance Agent",
  "Insurance Broker",
  "Insurance Company",
  "Intellectual Property Lawyer",
  "Interdenominational Church",
  "Interest",
  "Intergovernmental Organization",
  "Interior Design Studio",
  "Internet Cafe",
  "Internet Company",
  "Internet Lawyer",
  "Internet Service Provider",
  "Internist (Internal Medicine)",
  "Inventory Control Service",
  "Investing Service",
  "Investment Bank",
  "Investment Management Company",
  "Irani Restaurant",
  "Irish Pub",
  "Irish Restaurant",
  "Island",
  "Israeli Restaurant",
  "Italian Restaurant",
  "Jain Restaurant",
  "Jamaican Restaurant",
  "Janguh Restaurant",
  "Janitorial Service",
  "Japanese Restaurant",
  "Javanese Restaurant",
  "Jet Ski Rental",
  "Jewelry & Watches Company",
  "Jewelry & Watches Store",
  "Jewelry Wholesaler",
  "Jewelry/Watches",
  "Jiangsu Restaurant",
  "Jiangxi Restaurant",
  "Journalist",
  "Junior High School",
  "Junkyard",
  "Just For Fun",
  "Juvenile Lawyer",
  "Kaiseki Restaurant",
  "Karnataka Restaurant",
  "Kashmiri Restaurant",
  "Kebab Shop",
  "Kennel",
  "Kerala Restaurant",
  "Kids Entertainment Service",
  "Kingdom Hall",
  "Kitchen & Bath Contractor",
  "Kitchen/Cooking",
  "Kiteboarding Center",
  "Korean Restaurant",
  "Kosher Restaurant",
  "Kurdish Restaurant",
  "Kushikatsu Restaurant",
  "Labor & Employment Lawyer",
  "Labor Union",
  "Lake",
  "Landlord & Tenant Lawyer",
  "Landmark & Historical Place",
  "Landscape Company",
  "Language",
  "Language School",
  "Large Geo Area",
  "Laser Hair Removal Service",
  "Laser Tag Center",
  "Lasik/Laser Eye Surgeon",
  "Latin American Restaurant",
  "Laundromat",
  "Law Enforcement Agency",
  "Lawyer & Law Firm",
  "Lebanese Restaurant",
  "Legal",
  "Legal Service",
  "Library",
  "Light Rail Station",
  "Lighthouse",
  "Lighting Store",
  "Ligurian Restaurant",
  "Limo Service",
  "Lingerie & Underwear Store",
  "Literary Arts",
  "Live & Raw Food Restaurant",
  "Livery Stable",
  "Loan Service",
  "Lobbyist",
  "Local & Travel Website",
  "Local Service",
  "Locality",
  "Locksmith",
  "Lodge",
  "Logging Contractor",
  "Lombard Restaurant",
  "Lottery Retailer",
  "Lounge",
  "Luggage Service",
  "Lumber Yard",
  "Lutheran Church",
  "Macanese Restaurant",
  "Machine Shop",
  "Magazine",
  "Magician",
  "Maharashtrian Restaurant",
  "Maid & Butler",
  "Makeup Artist",
  "Malaysian Restaurant",
  "Malpractice Lawyer",
  "Manadonese Restaurant",
  "Management Service",
  "Manchu Restaurant",
  "Manufacturer/Supplier",
  "Marche Restaurant",
  "Marina",
  "Marine Service Station",
  "Marine Supply Store",
  "Marriage Therapist",
  "Martial Arts School",
  "Masonry Contractor",
  "Massage School",
  "Massage Service",
  "Massage Therapist",
  "Maternity & Nursing Clothing Store",
  "Maternity Clinic",
  "Mattress Manufacturer",
  "Mattress Store",
  "Mattress Wholesaler",
  "Meat Wholesaler",
  "Media",
  "Media Restoration Service",
  "Media/News Company",
  "Medical & Health",
  "Medical Cannabis Dispensary",
  "Medical Center",
  "Medical Device Company",
  "Medical Equipment Manufacturer",
  "Medical Equipment Supplier",
  "Medical Lab",
  "Medical Lawyer",
  "Medical Research Center",
  "Medical School",
  "Medical Service",
  "Medical Spa",
  "Medical Supply Store",
  "Meditation Center",
  "Mediterranean Restaurant",
  "Medium Geo Area",
  "Meeting Room",
  "Mennonite Church",
  "Men’s Clothing Store",
  "Mental Health Service",
  "Metal & Steel Company",
  "Metal Fabricator",
  "Metal Plating Service Company",
  "Metal Supplier",
  "Methodist Church",
  "Metro Area",
  "Mexican Restaurant",
  "Middle Eastern Restaurant",
  "Middle School",
  "Military Lawyer",
  "Miniature Golf Course",
  "Mining Company",
  "Mission",
  "Mobile Home Dealer",
  "Mobile Home Park",
  "Mobile Phone Shop",
  "Modeling Agency",
  "Modern European Restaurant",
  "Molecular Gastronomy Restaurant",
  "Molise Restaurant",
  "Mongolian Restaurant",
  "Monjayaki Restaurant",
  "Monument",
  "Mood",
  "Moroccan Restaurant",
  "Mortgage Brokers",
  "Mosque",
  "Motel",
  "Motivational Speaker",
  "Motor Vehicle Company",
  "Motorcycle Manufacturer",
  "Motorcycle Repair Shop",
  "Motorsports Store",
  "Mountain",
  "Mountain Biking Shop",
  "Movie",
  "Movie & Music Store",
  "Movie Character",
  "Movie Genre",
  "Movie/Television Studio",
  "Moving & Storage Service",
  "Moving Supply Store",
  "Mughalai Restaurant",
  "Music",
  "Music Award",
  "Music Chart",
  "Music Lessons & Instruction School",
  "Music Production Studio",
  "Music Video",
  "Musical Genre",
  "Musical Instrument",
  "Musical Instrument Store",
  "Musician",
  "Musician/Band",
  "Nabe Restaurant",
  "Nail Salon",
  "Nanny",
  "National Forest",
  "National Park",
  "Nationality",
  "Nature Preserve",
  "Naturopath",
  "Nazarene Church",
  "Neapolitan Restaurant",
  "Neighborhood",
  "Nepalese Restaurant",
  "Nephrologist",
  "Neurologist",
  "Neurosurgeon",
  "New American Restaurant",
  "News & Media Website",
  "News Personality",
  "Newspaper",
  "Newsstand",
  "Nicaraguan Restaurant",
  "Nigerian Restaurant",
  "Night Market",
  "Non-Business Places",
  "Nondenominational Church",
  "Non-Governmental Organization (NGO)",
  "Nonprofit Organization",
  "Noodle House",
  "North Indian Restaurant",
  "Not a Business",
  "Notary Public",
  "Nurseries & Gardening Store",
  "Nursing Agency",
  "Nursing Home",
  "Nursing School",
  "Nutritionist",
  "Obstetrician-Gynecologist (OBGYN)",
  "Occupational Safety and Health Service",
  "Occupational Therapist",
  "Ocean",
  "Office Equipment Store",
  "Office Supplies",
  "Oil Lube & Filter Service",
  "Okonomiyaki Restaurant",
  "Oncologist",
  "One-Time TV Program",
  "Onsen",
  "Ophthalmologist",
  "Optician",
  "Optometrist",
  "Oral Surgeon",
  "Orchestra",
  "Organic Grocery Store",
  "Orthodontist",
  "Orthopedist",
  "Orthotics & Prosthetics Service",
  "Osteopathic Doctor",
  "Other",
  "Otolaryngologist (ENT)",
  "Outdoor & Sporting Goods Company",
  "Outdoor Equipment Store",
  "Outdoor Recreation",
  "Outlet Store",
  "Padangnese Restaurant",
  "Paddleboarding Center",
  "Paintball Center",
  "Painting Lessons",
  "Pakistani Restaurant",
  "Palace",
  "Palatine Restaurant",
  "Panamanian Restaurant",
  "Paraguayan Restaurant",
  "Park",
  "Parking Garage / Lot",
  "Parsi Restaurant",
  "Party & Entertainment Service",
  "Party Entertainment Service",
  "Party Supply & Rental Shop",
  "Passport & Visa Service",
  "Patio/Garden",
  "Paving & Asphalt Service",
  "Pawn Shop",
  "Pediatric Dentist",
  "Pediatrician",
  "Pedicab Service",
  "Pentecostal Church",
  "Performance Art",
  "Performing Arts",
  "Performing Arts School",
  "Periodontist",
  "Persian/Iranian Restaurant",
  "Personal Assistant",
  "Personal Blog",
  "Personal Chef",
  "Personal Coach",
  "Personal Injury Lawyer",
  "Peruvian Restaurant",
  "Pest Control Service",
  "Pet Adoption Service",
  "Pet Breeder",
  "Pet Cafe",
  "Pet Cemetery",
  "Pet Groomer",
  "Pet Service",
  "Pet Sitter",
  "Pet Store",
  "Pet Supplies",
  "Petroleum Service",
  "Pharmaceutical Company",
  "Pharmaceuticals",
  "Pharmacy / Drugstore",
  "Pho Restaurant",
  "Phone/Tablet",
  "Photo Booth Service",
  "Photographer",
  "Photography Videography",
  "Physical Therapist",
  "Picnic Ground",
  "Piedmont Restaurant",
  "Pier",
  "Pilates Studio",
  "Pizza Place",
  "Plastic Company",
  "Plastic Fabricator",
  "Plastic Manufacturer",
  "Plastic Surgeon",
  "Playground",
  "Playlist",
  "Plumbing Service",
  "Podcast",
  "Podiatrist",
  "Poke Restaurant",
  "Polish Restaurant",
  "Polynesian Restaurant",
  "Pond",
  "Pop-Up Shop",
  "Port",
  "Portable Building Service",
  "Portable Toilet Rentals",
  "Portuguese Restaurant",
  "Postal Code",
  "Powder Coating Service",
  "Pregnancy Care Center",
  "Presbyterian Church",
  "Preschool",
  "Printing Service",
  "Private Investigator",
  "Private Members Club",
  "Private Plane Charter",
  "Private School",
  "Process Service",
  "Proctologist",
  "Producer",
  "Product Type",
  "Product/Service",
  "Professional Sports League",
  "Professional Sports Team",
  "Profile",
  "Promenade",
  "Property Lawyer",
  "Property Management Company",
  "Prosthodontist",
  "Province",
  "Psychiatrist",
  "Psychologist",
  "Psychotherapist",
  "Pub",
  "Public & Government Service",
  "Public Figure",
  "Public Garden",
  "Public School",
  "Public Service",
  "Public Square / Plaza",
  "Public Swimming Pool",
  "Public Toilet",
  "Public Utility Company",
  "Publisher",
  "Puerto Rican Restaurant",
  "Puglia Restaurant",
  "Pulmonologist",
  "Punjabi Restaurant",
  "Quay",
  "Racquetball Court",
  "Radio Station",
  "Radiologist",
  "Rafting/Kayaking Center",
  "Railroad Company",
  "Railway Station",
  "Rajasthani Restaurant",
  "Ramen Restaurant",
  "Real Estate",
  "Real Estate Agent",
  "Real Estate Appraiser",
  "Real Estate Company",
  "Real Estate Developer",
  "Real Estate Investment Firm",
  "Real Estate Lawyer",
  "Real Estate Service",
  "Real Estate Title & Development",
  "Record Label",
  "Recreation & Sports Website",
  "Recreation Center",
  "Recreation Spot",
  "Recruiter",
  "Recycling Center",
  "Reference Website",
  "Reflexologist",
  "Refrigeration Service",
  "Region",
  "Regional Website",
  "Religious Bookstore",
  "Religious Center",
  "Religious Organization",
  "Religious Place of Worship",
  "Religious School",
  "Rent to Own Store",
  "Rental Shop",
  "Reproductive Service",
  "Reptile Pet Store",
  "Reservoir",
  "Residence",
  "Restaurant",
  "Restaurant Supply Store",
  "Restaurant Wholesaler",
  "Retail Bank",
  "Retail Company",
  "Retirement & Assisted Living Facility",
  "Rheumatologist",
  "Rideshare Service",
  "River",
  "Robotics Company",
  "Rock Climbing Gym",
  "Rock Climbing Spot",
  "Rodeo",
  "Roller Skating Rink",
  "Roman Restaurant",
  "Romanian Restaurant",
  "Roofing Service",
  "Rose Garden",
  "Rugby Pitch",
  "Rugby Stadium",
  "Russian Restaurant",
  "RV Park",
  "RV Rental",
  "RV Repair Shop",
  "Safety & First Aid Service",
  "Sake Bar",
  "Salad Bar",
  "Salvadoran Restaurant",
  "Samgyetang Restaurant",
  "Sandblasting Service",
  "Sandwich Shop",
  "Sardinian Restaurant",
  "Satire/Parody",
  "Saxon Restaurant",
  "Scandinavian Restaurant",
  "School",
  "School Fundraiser",
  "School Sports League",
  "School Sports Team",
  "School Transportation Service",
  "Science",
  "Science Website",
  "Science, Technology & Engineering",
  "Scientist",
  "Scooter Rental",
  "Scottish Restaurant",
  "Screen Printing & Embroidery",
  "Scuba Diving Center",
  "Scuba Instructor",
  "Sculpture Garden",
  "Seafood Restaurant",
  "Seaplane Base",
  "Seasonal Store",
  "Secretarial Service",
  "Security Guard Service",
  "Self-Storage Facility",
  "Senegalese Restaurant",
  "Senior Center",
  "Septic Tank Service",
  "Service Apartments",
  "Seventh Day Adventist Church",
  "Sewer Service",
  "Sewing & Alterations",
  "Sex Therapist",
  "Shaanxi Restaurant",
  "Shabu Shabu Restaurant",
  "Shandong Restaurant",
  "Shanghainese Restaurant",
  "Shanxi Restaurant",
  "Shaved Ice Shop",
  "Shipping Supply & Service",
  "Shoe Repair Shop",
  "Shooting/Hunting Range",
  "Shopping & Retail",
  "Shopping District",
  "Shopping Mall",
  "Shopping Service",
  "Show",
  "Shredding Service",
  "Sicilian Restaurant",
  "Sightseeing Tour Agency",
  "Signs & Banner Service",
  "Sikh Temple",
  "Singaporean Restaurant",
  "Skate Shop",
  "Skateboard Park",
  "Ski & Snowboard School",
  "Ski & Snowboard Shop",
  "Ski Resort",
  "Skin Care Service",
  "Skydiving Center",
  "Slovakian Restaurant",
  "Small Geo Area",
  "Smog Emissions Check Station",
  "Smoothie & Juice Bar",
  "Snorkeling Spot",
  "Soba Restaurant",
  "Soccer Field",
  "Soccer Stadium",
  "Social Club",
  "Social Media Company",
  "Social Service",
  "Society & Culture Website",
  "Software",
  "Software Company",
  "Solar Energy Company",
  "Solar Energy Service",
  "Song",
  "Sorority & Fraternity",
  "Soul Food Restaurant",
  "Soup Restaurant",
  "South African Restaurant",
  "South Indian Restaurant",
  "South Tyrolean Restaurant",
  "Southern Restaurant",
  "Southwestern Restaurant",
  "Souvenir Shop",
  "Spa",
  "Spanish Restaurant",
  "Speakeasy",
  "Specialty Grocery Store",
  "Specialty School",
  "Speech Pathologist",
  "Speech Therapist",
  "Spiritual Leader",
  "Sport Psychologist",
  "Sporting Goods Store",
  "Sports",
  "Sports & Fitness Instruction",
  "Sports & Recreation",
  "Sports & Recreation Venue",
  "Sports Bar",
  "Sports Club",
  "Sports Event",
  "Sports League",
  "Sports Promoter",
  "Sports Season",
  "Sports Team",
  "Sportswear Store",
  "Squash Court",
  "Sri Lankan Restaurant",
  "Stadium, Arena & Sports Venue",
  "State",
  "State Park",
  "Stately Home",
  "Statue & Fountain",
  "STD Testing Center",
  "Steakhouse",
  "Storage Facility",
  "Street",
  "Structural Engineer",
  "Subcity",
  "Subneighborhood",
  "Subway Station",
  "Sugaring Service",
  "Sukiyaki Restaurant",
  "Sundanese Restaurant",
  "Sunglasses & Eyewear Store",
  "Supermarket",
  "Surf Shop",
  "Surfing Spot",
  "Surgeon",
  "Surgeries",
  "Surgical Center",
  "Surveyor",
  "Sushi Restaurant",
  "Swabian Restaurant",
  "Swimming Instructor",
  "Swimming Pool & Hot Tub Service",
  "Swimming Pool Cleaner",
  "Swimwear Store",
  "Swiss Restaurant",
  "Symphony",
  "Synagogue",
  "Syrian Restaurant",
  "Szechuan/Sichuan Restaurant",
  "Taco Restaurant",
  "Tai Chi Studio",
  "Taiwanese Restaurant",
  "Takoyaki Restaurant",
  "Talent Agent",
  "Tamilian Restaurant",
  "Tanning Salon",
  "Tapas Bar & Restaurant",
  "Tatar Restaurant",
  "Tattoo & Piercing Shop",
  "Tax Lawyer",
  "Tax Preparation Service",
  "Taxi Service",
  "Taxidermist",
  "Tea Room",
  "Teens & Kids Website",
  "Teeth Whitening Service",
  "Telecommunication Company",
  "Television Repair Service",
  "Television Service Provider",
  "Tempura Restaurant",
  "Tennis Court",
  "Tennis Stadium",
  "Teppanyaki Restaurant",
  "Test Preparation Center",
  "Tex-Mex Restaurant",
  "Textile Company",
  "Thai Restaurant",
  "Theatrical Play",
  "Theatrical Productions",
  "Theme Restaurant",
  "Therapist",
  "Threading Service",
  "Thrift & Consignment Store",
  "Tianjin Restaurant",
  "Ticket Sales",
  "Tiki Bar",
  "Tiling Service",
  "Time zone",
  "Tire Dealer & Repair Shop",
  "Tobacco Cessation Treatment Center",
  "Tobacco Company",
  "Tobacco Store",
  "Tonkatsu Restaurant",
  "Tools/Equipment",
  "Topic",
  "Tour Agency",
  "Tour Guide",
  "Tourist Information Center",
  "Towing Service",
  "Township",
  "Toy Store",
  "Track Stadium",
  "Trade School",
  "Traffic School",
  "Trailer Rental",
  "Train Station",
  "Transit Hub",
  "Transit Stop",
  "Transit System",
  "Translator",
  "Transportation Service",
  "Travel & Transportation",
  "Travel Agency",
  "Travel Company",
  "Travel Service",
  "Tree Cutting Service",
  "Trentino Alto Adige Restaurant",
  "Trinidadian Restaurant",
  "Trophies & Engraving Shop",
  "Truck Rental",
  "Truck Repair Shop",
  "Turkish Restaurant",
  "Tuscan Restaurant",
  "Tutor/Teacher",
  "TV",
  "TV & Movies",
  "TV Channel",
  "TV Genre",
  "TV Network",
  "TV Season",
  "TV Show",
  "TV/Movie Award",
  "Udon Restaurant",
  "Udupi Restaurant",
  "Ukrainian Restaurant",
  "Umbrian Restaurant",
  "Unagi Restaurant",
  "Uniform Supplier",
  "University (NCES)",
  "University Status",
  "Urologist",
  "Uruguayan Restaurant",
  "Uttar Pradesh Restaurant",
  "Uzbek Restaurant",
  "Vacation Home Rental",
  "Vegetarian/Vegan Restaurant",
  "Vending Machine Sales & Service",
  "Venetian Restaurant",
  "Venezuelan Restaurant",
  "Veterinarian",
  "Video",
  "Video Creator",
  "Video Game",
  "Video Game Store",
  "Vietnamese Restaurant",
  "Village",
  "Vintage Store",
  "Vinyl Siding Company",
  "Visual Arts",
  "Vitamin Supplement Shop",
  "Vitamins/Supplements",
  "Volcano",
  "Volleyball Court",
  "Wagashi Restaurant",
  "Waste Management Company",
  "Water Heater Installation & Repair Service",
  "Water Treatment Service",
  "Water Utility Company",
  "Waterfall",
  "Waxing Service",
  "Weather Station",
  "Web Designer",
  "Website",
  "Wedding Planning Service",
  "Wedding Venue",
  "Weight Loss Center",
  "Well Water Drilling Service",
  "Wheel & Rim Repair Service",
  "Whisky Bar",
  "Wholesale & Supply Store",
  "Wholesale Bakery",
  "Wholesale Grocer",
  "Wig Store",
  "Window Installation Service",
  "Wine Bar",
  "Wine, Beer & Spirits Store",
  "Wine/Spirits",
  "Winery/Vineyard",
  "Women’s Clothing Store",
  "Women’s Health Clinic",
  "Work Position",
  "Work Project",
  "Work Status",
  "Writer",
  "Writing Service",
  "Xinjiang Restaurant",
  "Yakiniku Restaurant",
  "Yakitori Restaurant",
  "Yoga Studio",
  "Yoshoku Restaurant",
  "Youth Organization",
  "Yunnan Restaurant",
  "Zhejiang Restaurant",
];



export function createError(statusCode, message, data) {
  const error = new Error(message);
  error.statusCode = statusCode;
  if (data) {
    error.data = data;
  }
  throw error;
}
